import html

CSS = """
body {
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, "Helvetica Neue", Arial;
    margin: 24px;
    background: #f6f6f6;
    color: #222;
}

h1 {
    margin-bottom: 12px;
}

.grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
    gap: 18px;
}

.card {
    background: #fff;
    border: 1px solid #e5e5e5;
    padding: 12px;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.03);
}

.thumb {
    max-width: 100%;
    height: auto;
    display: block;
    margin-bottom: 8px;
    border-radius: 4px;
}

.meta {
    font-size: 13px;
    color: #666;
    margin-bottom: 8px;
}

pre.ascii {
    font-family: "Courier New", Courier, monospace;
    font-size: 10px;
    line-height: 10px;
    overflow: auto;
    background: #111;
    color: #e6e6e6;
    padding: 8px;
    border-radius: 6px;
    max-height: 420px;
}

.row {
    display: flex;
    gap: 12px;
    align-items: flex-start;
}

.col-left {
    flex: 0 0 120px;
}

.col-right {
    flex: 1 1 auto;
}

.small {
    font-size: 12px;
    color: #444;
}

.footer {
    margin-top: 18px;
    font-size: 13px;
    color: #666;
}
"""


def generate_gallery_html(items, out_html_path: str, title="ASCII Art Gallery"):
    parts = [
        "<!doctype html>",
        "<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>",
        f"<title>{html.escape(title)}</title>",
        f"<style>{CSS}</style>",
        "</head><body>",
        f"<h1>{html.escape(title)}</h1>",
        "<div class='grid'>",
    ]
    for it in items:
        ascii_html = html.escape(it["ascii_text"])
        meta_line = f"{it['filename']} — original {it['orig_w']}×{it['orig_h']} — ascii {it['ascii_w']}×{it['ascii_h']} — {it['proc_time']}"
        card = f"""
        <div class="card">
          <div class="row">
            <div class="col-left">
              <img class="thumb" src="{html.escape(it["thumb_rel"])}" alt="{html.escape(it["filename"])}">
              <div class="small">{html.escape(meta_line)}</div>
            </div>
            <div class="col-right">
              <pre class="ascii">{ascii_html}</pre>
            </div>
          </div>
        </div>
        """
        parts.append(card)
    parts.append("</div>")
    parts.append(
        "<div class='footer'>Generated by <a href='https://github.com/Nate534/image_to_ascii'>IMAGE_TO_ASCII</a></div>"
    )
    parts.append("</body></html>")
    with open(out_html_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
